### ISSUE TITLE
ci(perf): experimental Angular Linker support

### ISSUE THREAD

**Issue by NachoVazquez** [ngworker/lumberjack#112]
In separate CI workflow logic branches/matrix legs:
1. Set `enableIvy: true` in `build` step. Supported by `ng-packagr` version `11.1.0`. Switch to `@angular-devkit/build-angular:ng-packagr`.
1. For the app, use `@angular-devkit/build-angular` version `>=11.1.0`.
1. Change `tsconfig.lib.prod.json` as seen in [this example](https://github.com/mgechev/ivy-library-distribution-demo#readme).

See https://github.com/angular/angular-cli/commit/35d8adf02002115f5d6c2964c261f9336297abb8.
See https://dev.to/angular/understanding-angular-ivy-library-compilation-246n.

**Comment by LayZeeDK** [comment]
Closing as partial Ivy compilation is stable since Angular CLI version 12.2.
