### ISSUE TITLE
Automate Lumberjack releases

### ISSUE THREAD

**Issue by NachoVazquez** [ngworker/lumberjack#134]
## The Problem

Currently, the release of the new Lumberjack version is a manual and tedious task.

## The Goal

Automate the release of new versions using GH Actions.

**Comment by patelvimal** [comment]
@NachoVazquez I did the same thing in one of my angular package. Here is the link:-
https://github.com/patelvimal/ng-vim-devtools/blob/master/.github/workflows/npm-publish.yml

Whenever I publish using Github then this action gets triggered and will publish the package in npm.

**Comment by ajitzero** [comment]
@NachoVazquez There's a new package to set all this up automatically for Nx repos: https://github.com/kreuzerk/nx-release by @kreuzerk

I recently set this up for my own project, and the steps are very simple to follow.

**Comment by NachoVazquez** [comment]
Hi @ajitzero this is actually already addressed. I forgot to update the ticket. We are using https://github.com/jscutlery/semver. That said we have faced some issues with it. 

I will be happy to accept a PR with the migration if you are interested. 

In the meantime I will take a look at this package. 

Thank you!

**Comment by ajitzero** [comment]
I updated my comment above with more details. Please read again if it's at all needed, but if the current setup works fine then I don't think we should migrate anything.

**Comment by NachoVazquez** [comment]
From what I see, we have all this covered by the package I mentioned, we were having some issues with permissions, but the link you provided gave me a few ideas about how to fix it. Thanks for sharing!

I'm going to close this issue since it is already addressed. If you think we should change something in the current workflow, feel free to create a new issue :)
