### ISSUE TITLE
Migrate all TypeScript private properties to JavaScript private properties (#)

### ISSUE THREAD

**Issue by NachoVazquez** [ngworker/lumberjack#142]
## The Problem

Most private properties of the project are using the Typescript `private` indicator instead of the native ES private properties (#).

ESLint private properties are better for libraries since they actually prohibit consumers from accessing the properties, even at runtime. This prevents unwanted dependencies on library internals. 

## Acceptance Criteria

Migrate all Typescript private properties to ESLint private properties.

**Comment by santoshyadavdev** [comment]
Hey @NachoVazquez, 
Let me know if this is ready for development.

**Comment by NachoVazquez** [comment]
Sadly, this PR hasn't been merged yet https://github.com/cartant/eslint-plugin-rxjs-angular/pull/12.

We have a couple of options here. 

1. Drop `eslint-plugin-rxjs-angular` seems it is unmaintained by now
2. Fork `eslint-plugin-rxjs-angular` and start maintaining it ourselves
3. Try to reach Cartant and see if he plans to maintain the project

Any thoughts @LayZeeDK ?
