### ISSUE TITLE
Configuring and adding custom log levels for Lumberjack Loggers and its log-drivers

### ISSUE THREAD

**Issue by SaI7Tejashwin** [ngworker/lumberjack#151]
Is it possible to configure custom log levels (based on severity) of type LumberjackLogLevel and how to configure it to support the log-drivers with the custom levels? The documentation (and the underlying code) shows that the log levels are predefined and I'm not sure how to approach this.

**Comment by NachoVazquez** [comment]
I understand you are asking to add a custom `LumberjackLogLevel` like `LumberjackLogLevel.moreThanCritical` or something like that.

Is that correct?

Why is not enough with the existing LogLevels?

**Comment by SaI7Tejashwin** [comment]
Understood, that makes sense. I'll work around with a custom level at the Payload for the time being. Thanks for the help.
