### ISSUE TITLE
Angular 19 compatibility

### ISSUE THREAD

**Issue by Schoude** [ngworker/lumberjack#213]
## Describe the bug

Can't install this package in Angular 19 project.

## To Reproduce

Run `npm install @ngworker/lumberjack` for an Angular 19 project.

## Expected behavior

Should be able to install without using `npm install --force`.

## Environment

- OS: Windows 10
- Lumberjack Version 18.0.0
- Angular version: 19.0.0

**Comment by NachoVazquez** [comment]
Yep, we haven't yet migrated the package to Angular 19. I'll try to do it tonight.

**Comment by NachoVazquez** [comment]
@Schoude a new version has been released with support for Angular 19
